### ISSUE TITLE
development stopped?

### ISSUE THREAD

**Issue by gothmog123** [J-Lentz/iwgtk#12]
this was the best thing ever :(

**Comment by J-Lentz** [comment]
Development hasn't stopped, although it has slowed down considerably since the project has reached a state that I'm mostly happy with. When I have more time in the future, I'm planning to round out some rough edges, implement some nice-to-have features, and port to GTK4. In the meantime, I'm happy to accept any pull requests.

**Comment by gothmog123** [comment]
thanks, glad to hear
