### ISSUE TITLE
No indicator icons in XFCE on Void Linux

### ISSUE THREAD

**Issue by basploeger** [J-Lentz/iwgtk#21]
I run `iwgtk -i` and do not see indicator icons appearing in the system tray (Status Tray plugin) of the XFCE 4.16 panel. I believe the XFCE tray supports the Status Notifier API.

**Comment by J-Lentz** [comment]
It works for me in Arch Linux using xfce4-panel 4.16.3.

In qdbusviewer or an equivalent program, do you see an `org.kde.StatusNotifierWatcher` service? And after launching `iwgtk -i`, does a new `org.kde.StatusNotifierItem` appear?

**Comment by basploeger** [comment]
Yes, I do see a new `org.kde.StatusNotifierItem` appear when I start `iwgtk -i`, but I do not see those other services running. I'm on Void linux. Guess I need to install some package?

**Comment by basploeger** [comment]
By the way, the relevant versions:
- xfce4-panel: 4.16.3
- iwgtk: 0.4

**Comment by J-Lentz** [comment]
Hmm, strange. No packages should be required except xfce4-panel and the status tray plugin, which in Arch Linux, is included with xfce4-panel. Are you sure that you have the status tray plugin enabled on your panel?

**Comment by basploeger** [comment]
Yes. To be sure, I removed and added it again, but to no avail :(
![Screenshot_2021-12-29_00-32-27](https://user-images.githubusercontent.com/5904333/147614737-7dd0e9e4-5b3c-4dad-9db8-f47d0a5128bd.png)

**Comment by basploeger** [comment]
Thanks for the help so far. I'm going further down the rabbit hole here :) : 
https://forum.xfce.org/viewtopic.php?pid=65392

I will report back here when that turns up something useful.

**Comment by J-Lentz** [comment]
Based on ToZ's response in that thread, Void's xfce4-panel package appears to be built without StatusNotifierItem support. The statusnotifier.py script displays an icon because it uses libappindicator, which attempts to use SNI and falls back to XEmbed if SNI support isn't available. Whereas iwgtk uses SNI directly and has no XEmbed fallback mode.

One workaround is to use an SNI-to-XEmbed compatibility layer, such as this one: https://git.sr.ht/~steef/snixembed

It may be worthwhile to check with the maintainer of Void's xfce4-panel package whether omitting SNI support is intentional, or a bug.

**Comment by basploeger** [comment]
Thanks. I added SNI support to the Void package and verified it works: the iwgtk icon appears in the modified build.

**Comment by J-Lentz** [comment]
Cool, so it's just a matter of installing libdbusmenu-gtk3 before building xfce4-panel?

**Comment by basploeger** [comment]
Yes, xfce4-panel's configure script will then pick it up and enable StatusNotifier support.
