### ISSUE TITLE
iwd is not running

### ISSUE THREAD

**Issue by Seiryu-uwu** [J-Lentz/iwgtk#24]
when trying to launch iwgtk it says iwd is not running

**Comment by J-Lentz** [comment]
1. What's the output of `systemctl status iwd` (or some equivalent command if you don't use systemd)?
2. Assuming that iwd is in fact running, does `iwctl` work in your non-root user account?

**Comment by Seiryu-uwu** [comment]
1.○ iwd.service - Wireless service
     Loaded: loaded (/usr/lib/systemd/system/iwd.service; disabled; vendor preset: disabled)
     Active: inactive (dead)
2.no
3.1.27-1

**Comment by J-Lentz** [comment]
The first thing you need to do is disable and stop wpa_supplicant (I'm assuming you're using it currently, since you have iwd disabled), and then enable and start iwd:
`# systemctl disable --now wpa_supplicant`
`# systemctl enable --now iwd`

Because you're using a recent version of iwd (>=1.23), you'll also need to add your user account to the `netdev` group:
`# usermod -a -G netdev YOUR_USER_ACCOUNT`

You might need to log out and back in afterward for the `netdev` group membership to take effect. Hopefully this helps.

**Comment by Seiryu-uwu** [comment]
when I try to usermod it says that group netdev does not exist

**Comment by J-Lentz** [comment]
In that case, you'll need to issue `# groupadd netdev` before the `usermod` command.

**Comment by Seiryu-uwu** [comment]
It is working now ty very much
